/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author C.B.RAMKISHAN
 */
public class page6 extends javax.swing.JFrame {
    
    
     
    /**
     * Creates new form page6
     */
    public page6(String name,String depar,String dat,String blood,String mobile,String ca1,String ca2,String ca3,String mail,String employee,String ca4 ) {
        initComponents();
        na.setText(name);
        dp.setText(depar);
        date.setText(dat);
        bd.setText(blood);
        mb.setText(mobile);
        a1.setText(ca1);
        a2.setText(ca2);
        a3.setText(ca3);
        a4.setText(ca4);
        mai.setText(mail);
        em.setText(employee);
        //img.setIcon();
        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        na = new javax.swing.JLabel();
        dp = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        a1 = new javax.swing.JLabel();
        mb = new javax.swing.JLabel();
        bd = new javax.swing.JLabel();
        a2 = new javax.swing.JLabel();
        a3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        a4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        em = new javax.swing.JLabel();
        mai = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel18.setText("jLabel18");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 255));
        setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        setPreferredSize(new java.awt.Dimension(640, 490));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("NAME :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 290, 56, 21);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(254, 300, 74, 0);

        na.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        na.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(na);
        na.setBounds(100, 290, 143, 21);

        dp.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        dp.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(dp);
        dp.setBounds(43, 320, 180, 21);
        getContentPane().add(img);
        img.setBounds(80, 150, 130, 130);

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 153));
        jLabel6.setText("DOB :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(330, 60, 60, 21);

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 153));
        jLabel7.setText("BLOOD GROUP :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(330, 90, 130, 20);

        date.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        date.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(date);
        date.setBounds(380, 60, 120, 20);

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 153));
        jLabel9.setText("MOBILE :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(330, 120, 80, 30);

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 0, 153));
        jLabel10.setText("ADDRESS :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(380, 170, 110, 21);

        a1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        a1.setForeground(new java.awt.Color(51, 51, 255));
        getContentPane().add(a1);
        a1.setBounds(370, 200, 170, 30);

        mb.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        mb.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(mb);
        mb.setBounds(410, 120, 160, 30);

        bd.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        bd.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(bd);
        bd.setBounds(470, 80, 100, 40);

        a2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        a2.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(a2);
        a2.setBounds(370, 230, 180, 30);

        a3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        a3.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(a3);
        a3.setBounds(370, 250, 210, 40);

        jLabel16.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 0, 153));
        jLabel16.setText("E-MAIL :");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(320, 330, 70, 30);

        a4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        a4.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(a4);
        a4.setBounds(340, 370, 210, 30);

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("EMP NO :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 350, 72, 20);

        em.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        em.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(em);
        em.setBounds(120, 350, 110, 20);

        mai.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        mai.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(mai);
        mai.setBounds(370, 280, 200, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\C.B.RAMKISHAN\\Downloads\\vcetid2.jpg")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(310, 30, 270, 390);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\C.B.RAMKISHAN\\Downloads\\staffid.jpg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 40, 240, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(page6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(page6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(page6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(page6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new page6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a2;
    private javax.swing.JLabel a3;
    private javax.swing.JLabel a4;
    private javax.swing.JLabel bd;
    private javax.swing.JLabel date;
    private javax.swing.JLabel dp;
    private javax.swing.JLabel em;
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel mai;
    private javax.swing.JLabel mb;
    private javax.swing.JLabel na;
    // End of variables declaration//GEN-END:variables
}
