
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author C.B.RAMKISHAN
 */
public class Page5 extends javax.swing.JFrame {
    
    
    
    String names,depart,date,blood,mobile,ca1,ca2,ca3,ca4,mai,employee; 

    /**
     * Creates new form Page5
     */
    public Page5() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        n1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        da = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bl = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ml = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        de = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        c1 = new javax.swing.JTextField();
        c2 = new javax.swing.JTextField();
        c3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        sub = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        emp = new javax.swing.JTextField();
        c4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        b1.setIcon(new javax.swing.ImageIcon("C:\\Users\\C.B.RAMKISHAN\\Downloads\\STAFF.jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 255));
        setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        setPreferredSize(new java.awt.Dimension(610, 900));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ENTER THE DETAILS OF STAFFS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(25, 51, 486, 53);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("NAME ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(16, 160, 100, 38);

        n1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(n1);
        n1.setBounds(163, 157, 360, 38);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("DOB");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(16, 260, 120, 50);

        da.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(da);
        da.setBounds(160, 260, 360, 39);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("BLOOD GROUP");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(18, 310, 122, 60);

        bl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blActionPerformed(evt);
            }
        });
        getContentPane().add(bl);
        bl.setBounds(160, 320, 360, 37);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 255));
        jLabel5.setText("MOBILE  ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(16, 370, 80, 40);

        ml.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(ml);
        ml.setBounds(160, 370, 360, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 255));
        jLabel6.setText("ADDRESS");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 430, 180, 40);

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 780, 175, 46);

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        jButton2.setText("GET ID");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(400, 780, 167, 50);
        getContentPane().add(de);
        de.setBounds(160, 210, 360, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 255));
        jLabel10.setText("PROFESSOR TYPE");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 220, 150, 30);

        c1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(c1);
        c1.setBounds(150, 430, 380, 40);

        c2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        getContentPane().add(c2);
        c2.setBounds(150, 480, 380, 40);

        c3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(c3);
        c3.setBounds(150, 530, 380, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 255));
        jLabel8.setText("E-MAIL");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 700, 110, 40);

        sub.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(sub);
        sub.setBounds(160, 640, 370, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 255));
        jLabel7.setText("EMPLOYEE NO");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 640, 160, 40);
        getContentPane().add(emp);
        emp.setBounds(140, 700, 390, 40);

        c4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(c4);
        c4.setBounds(150, 580, 380, 40);

        jButton3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton3.setText("SET IMAGE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(230, 780, 140, 50);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\C.B.RAMKISHAN\\Downloads\\CHILD.jpg")); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 600, 850);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         names=n1.getText();
         depart=de.getText();
         date=da.getText();
         blood=bl.getText();
         mobile=ml.getText();
         ca1=c1.getText();
         ca2=c2.getText();
         ca3=c3.getText();
         ca4=c4.getText();
         mai=sub.getText();
         employee=emp.getText();
         new page6(names,depart,date,blood,mobile,ca1,ca2,ca3,ca4,mai,employee);
      //  new page6().setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Page2().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void blActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       JFileChooser file=new JFileChooser();
       file.setCurrentDirectory(new File("user.dir"));
        
        FileNameExtensionFilter filter=new FileNameExtensionFilter("All pic","png","jpg","jpeg","gif");
        file.addChoosableFileFilter(filter);
        
        file.showSaveDialog(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Page5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b1;
    private javax.swing.JTextField bl;
    private javax.swing.JTextField c1;
    private javax.swing.JTextField c2;
    private javax.swing.JTextField c3;
    private javax.swing.JTextField c4;
    private javax.swing.JTextField da;
    private javax.swing.JTextField de;
    private javax.swing.JTextField emp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField ml;
    private javax.swing.JTextField n1;
    private javax.swing.JTextField sub;
    // End of variables declaration//GEN-END:variables
}
