
import java.io.File;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author C.B.RAMKISHAN
 */
import java.io.File;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.PrintJob;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
public class Page3 extends javax.swing.JFrame {

    /**
     * Creates new form Page3
     */
    static Image g;
    String names,dobs,roll,degrees,address,batches,ad1,ad2,ad3,mob,par,bloods,gmail,path;
   //byte[] icon;
    public Page3() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dob = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rollno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        batch = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        blood = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        parent = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        A4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        addres = new javax.swing.JTextField();
        a1 = new javax.swing.JTextField();
        a2 = new javax.swing.JTextField();
        a3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        degree = new javax.swing.JTextField();
        setimage = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\C.B.RAMKISHAN\\Downloads\\CHILD.jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(620, 980));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("NAME        ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(23, 170, 130, 37);

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ENTER THE DETAILS OF STUDENTS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(6, 36, 590, 74);

        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(180, 170, 310, 37);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("DOB          ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(23, 220, 130, 36);

        dob.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobActionPerformed(evt);
            }
        });
        getContentPane().add(dob);
        dob.setBounds(180, 220, 310, 36);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("ROLLNO        ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(24, 270, 140, 28);

        rollno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(rollno);
        rollno.setBounds(180, 270, 310, 36);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 255));
        jLabel6.setText("BATCH    ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 320, 130, 36);

        batch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        batch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchActionPerformed(evt);
            }
        });
        getContentPane().add(batch);
        batch.setBounds(180, 320, 310, 40);

        jLabel7.setBackground(new java.awt.Color(204, 204, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 255));
        jLabel7.setText("BLOOD GROUP  ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 430, 150, 38);

        blood.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        blood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodActionPerformed(evt);
            }
        });
        getContentPane().add(blood);
        blood.setBounds(180, 430, 310, 38);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 255));
        jLabel8.setText("PARENT NAME ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 474, 140, 50);

        parent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        parent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentActionPerformed(evt);
            }
        });
        getContentPane().add(parent);
        parent.setBounds(180, 480, 310, 42);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 255));
        jLabel9.setText("MOBILE          ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(24, 530, 140, 50);

        mobile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileActionPerformed(evt);
            }
        });
        getContentPane().add(mobile);
        mobile.setBounds(180, 530, 310, 39);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 255));
        jLabel10.setText("ADDRESS        ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 580, 134, 50);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 255));
        jLabel11.setText("E-MAIL          ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 790, 134, 50);

        mail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(mail);
        mail.setBounds(150, 807, 350, 30);

        A4.setBackground(new java.awt.Color(255, 204, 204));
        A4.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        A4.setText("BACK");
        A4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A4ActionPerformed(evt);
            }
        });
        getContentPane().add(A4);
        A4.setBounds(20, 870, 125, 33);

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jButton1.setText("GET ID");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(470, 870, 114, 37);

        addres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(addres);
        addres.setBounds(180, 580, 310, 40);

        a1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(a1);
        a1.setBounds(180, 630, 310, 40);

        a2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(a2);
        a2.setBounds(180, 680, 310, 40);

        a3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(a3);
        a3.setBounds(180, 730, 310, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 255));
        jLabel5.setText("DEGREE        ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 380, 130, 40);
        getContentPane().add(degree);
        degree.setBounds(180, 380, 310, 40);

        setimage.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        setimage.setForeground(new java.awt.Color(153, 0, 153));
        setimage.setText("SET IMAGE");
        setimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setimageActionPerformed(evt);
            }
        });
        getContentPane().add(setimage);
        setimage.setBounds(230, 860, 140, 50);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\C.B.RAMKISHAN\\Downloads\\CHILD.jpg")); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, -30, 650, 990);
        getContentPane().add(image);
        image.setBounds(610, 390, 280, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nameActionPerformed

    private void dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobActionPerformed

    private void A4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A4ActionPerformed
        // TODO add your handling code here:
        new Page2().setVisible(true);
    }//GEN-LAST:event_A4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        ImageIcon icon;
         
        names=name.getText();
        dobs=dob.getText();
        roll=rollno.getText();
        degrees=degree.getText();
        address=addres.getText();
        batches=batch.getText();
        ad1=a1.getText();
        ad2=a2.getText();
        ad3=a3.getText();
        mob=mobile.getText();
        par=parent.getText();
        bloods=blood.getText();
        gmail=mail.getText();
        icon=(ImageIcon)setimage.getIcon();
        
     new page4(names,dobs,roll,degrees,address,batches,ad1,ad2,ad3,mob,par,bloods,gmail);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodActionPerformed

    private void parentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parentActionPerformed

    private void mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileActionPerformed

    private void batchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batchActionPerformed

    private void setimageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setimageActionPerformed
            //  TODO add your handling code here:
           //  JFileChooser file=new JFileChooser();
          //  file.setCurrentDirectory(new File("user.dir"));
         //
        // FileNameExtensionFilter filter=new FileNameExtensionFilter("All pic","png","jpg","jpeg","gif");
       // file.addChoosableFileFilter(filter);
      // Image getAbsolutePath = null;
     //file.showSaveDialog(null);
        
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File file=chooser.getSelectedFile();
        String path=file.getAbsolutePath();
        
     /*   Image im=Toolkit.getDefaultToolkit().createImage(path);
        im=im.getScaledInstance(setimage.getWidth(),setimage.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon li=new ImageIcon(im);
        image.setIcon(li);*/
        String Image;
        
        
     //   new page4(Image image);
        
        
        
        
        
        
        
    }//GEN-LAST:event_setimageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Page3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A4;
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField a3;
    private javax.swing.JTextField addres;
    private javax.swing.JTextField batch;
    private javax.swing.JTextField blood;
    private javax.swing.JTextField degree;
    private javax.swing.JTextField dob;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField name;
    private javax.swing.JTextField parent;
    private javax.swing.JTextField rollno;
    private javax.swing.JButton setimage;
    // End of variables declaration//GEN-END:variables

   private static class JfileChooser {

        public JfileChooser() {
        }

        private void showOpenDialog(Object object) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        private File getSelectedfile() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }

    private static class Jfilechooser {

        public Jfilechooser() {
        }
    }
}
